services:
  zookeeper:
    image: "bitnami/zookeeper:3.8" # Versi spesifik untuk zookeeper juga baik
    container_name: zookeeper
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - "2181:2181"

  kafka:
    image: "bitnami/kafka:3.3.2" # Coba versi ini dulu
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      # Konfigurasi untuk mode Zookeeper
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181 # Penting untuk mode Zookeeper
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - KAFKA_LISTENERS=PLAINTEXT://:9092 # Untuk internal container
      - ALLOW_PLAINTEXT_LISTENER=yes # Biasanya untuk kompatibilitas
    depends_on:
      - zookeeper
